services:
  gamers_db:
    image: postgres:17
    container_name: gamers_db
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - gamers_erp_data:/var/lib/postgresql/data

volumes:
  gamers_erp_data: